### PR TITLE
remove the updae popup from the github repo because its useless(github is never up to date) and removed the need of using a key to use the swapper

### PR DESCRIPTION
**Pull request by maxiwee69**

### CODE REVIEW

**Comment by maxiwee69** [comment]
Why?

**Comment by CodeWslt** [comment]
> Why?

It benefits nothing to the project. Why would I keep it open?

**Comment by maxiwee69** [comment]
Why don’t you actually keep the GitHub up to date with the version on the website?

**Comment by CodeWslt** [comment]
> Why don’t you actually keep the GitHub up to date with the version on the website?

It was on the dev branch I just forgot to merge it to the main. It's fixed now.

**Pull request closed without merging**
